version: '3'
services:
    server:
        build: 
            dockerfile: Dockerfile
            context: ./server
        image: "dockerkub8.azurecr.io/country_club_server" 
        ports:
          - "3000:3000"
            # stdin_open: true
    
    client: 
        build: 
          dockerfile: Dockerfile
          context: ./client
        image: "dockerkub8.azurecr.io/country_club_client" 
        ports:
          - "80:4000"
        stdin_open: true
        links:
          - "server"
        